/* Auto-generated by tools/wav_to_pwm.py — do not edit. */
/* Source: sliding.wav */
#ifndef AMB_SLIDING_H
#define AMB_SLIDING_H
#include <stdint.h>

#define AMB_SLIDING_SAMPLE_COUNT 5976
#define AMB_SLIDING_SAMPLE_RATE  11025
#define AMB_SLIDING_SAMPLE_BITS  8

extern const int8_t amb_sliding_samples[5976];

#endif
