/* Auto-generated by tools/wav_to_pwm.py — do not edit. */
/* Source: ES_Electricity, Buzz & Hum, Lights, Electrical Hum - Epidemic Sound.wav */
#ifndef AMB_BUZZ_H
#define AMB_BUZZ_H
#include <stdint.h>

#define AMB_BUZZ_SAMPLE_COUNT 448000
#define AMB_BUZZ_SAMPLE_RATE  16000
#define AMB_BUZZ_SAMPLE_BITS  16

extern const uint16_t amb_buzz_samples[448000];

#endif
