/* Auto-generated by tools/wav_to_pwm.py — do not edit. */
/* Source: crt_off.wav */
#ifndef AMB_CRT_OFF_H
#define AMB_CRT_OFF_H
#include <stdint.h>

#define AMB_CRT_OFF_SAMPLE_COUNT 3055
#define AMB_CRT_OFF_SAMPLE_RATE  8000
#define AMB_CRT_OFF_SAMPLE_BITS  8

extern const int8_t amb_crt_off_samples[3055];

#endif
