/* Auto-generated by tools/wav_to_pwm.py — do not edit. */
/* Source: crt_degauss_short.wav */
#ifndef AMB_CRT_ON_H
#define AMB_CRT_ON_H
#include <stdint.h>

#define AMB_CRT_ON_SAMPLE_COUNT 17658
#define AMB_CRT_ON_SAMPLE_RATE  8000
#define AMB_CRT_ON_SAMPLE_BITS  8

extern const int8_t amb_crt_on_samples[17658];

#endif
