/* Auto-generated by tools/wav_to_pwm.py — do not edit. */
/* Source: shuffle.wav */
#ifndef AMB_SHUFFLE_H
#define AMB_SHUFFLE_H
#include <stdint.h>

#define AMB_SHUFFLE_SAMPLE_COUNT 5640
#define AMB_SHUFFLE_SAMPLE_RATE  11025
#define AMB_SHUFFLE_SAMPLE_BITS  8

extern const int8_t amb_shuffle_samples[5640];

#endif
