/* Auto-generated by tools/adpcm_bake.py — do not edit. */
/* Source: Voyager_Golden_Record_-_Greetings_In_55_Languages.mp3 */
#ifndef AMB_HELLO_ADP_H
#define AMB_HELLO_ADP_H
#include <stdint.h>

#define AMB_HELLO_ADP_SAMPLE_COUNT 1591032
#define AMB_HELLO_ADP_SAMPLE_RATE  6000
#define AMB_HELLO_ADP_DATA_BYTES   795516

extern const uint8_t amb_hello_adp_data[795516];

#endif
