/* Auto-generated by tools/wav_to_pwm.py — do not edit. */
/* Source: Voyager_Golden_Record_-_Greetings_In_55_Languages.mp3 */
#ifndef AMB_DEATH_TAPE_H
#define AMB_DEATH_TAPE_H
#include <stdint.h>

#define AMB_DEATH_TAPE_SAMPLE_COUNT 24000
#define AMB_DEATH_TAPE_SAMPLE_RATE  6000
#define AMB_DEATH_TAPE_SAMPLE_BITS  8

extern const int8_t amb_death_tape_samples[24000];

#endif
