/* Auto-generated by tools/wav_to_pwm.py — do not edit. */
/* Source: ES_Footsteps, Human, Carpet, Walking, Medium - Epidemic Sound.wav */
#ifndef AMB_STEP_H
#define AMB_STEP_H
#include <stdint.h>

#define AMB_STEP_SAMPLE_COUNT 33075
#define AMB_STEP_SAMPLE_RATE  11025
#define AMB_STEP_SAMPLE_BITS  16

extern const uint16_t amb_step_samples[33075];

#endif
