/* Auto-generated by tools/wav_to_pwm.py — do not edit. */
/* Source: ES_Electricity, Buzz & Hum, Electric, Neon, Light - Epidemic Sound.wav */
#ifndef AMB_NEON_H
#define AMB_NEON_H
#include <stdint.h>

#define AMB_NEON_SAMPLE_COUNT 32000
#define AMB_NEON_SAMPLE_RATE  16000
#define AMB_NEON_SAMPLE_BITS  16

extern const uint16_t amb_neon_samples[32000];

#endif
