/* Auto-generated by tools/wav_to_pwm.py — do not edit. */
/* Source: ES_Footsteps, Human, Carpet, Walking, Medium - Epidemic Sound.wav */
#ifndef AMB_STEP_H
#define AMB_STEP_H
#include <stdint.h>

#define AMB_STEP_SAMPLE_COUNT 18000
#define AMB_STEP_SAMPLE_RATE  6000
#define AMB_STEP_SAMPLE_BITS  8

extern const int8_t amb_step_samples[18000];

#endif
