/* Auto-generated by tools/wav_to_pwm.py — do not edit. */
/* Source: golden.wav */
#ifndef AMB_HELLO_H
#define AMB_HELLO_H
#include <stdint.h>

#define AMB_HELLO_SAMPLE_COUNT 180000
#define AMB_HELLO_SAMPLE_RATE  6000
#define AMB_HELLO_SAMPLE_BITS  8

extern const int8_t amb_hello_samples[180000];

#endif
