/* AUTO-GENERATED by tools/gen_assets.py from registry.json.
 * Community sprite palettes -> CRAM arena entries. Painted by
 * build_palette(); do NOT edit. */
#ifndef COMM_PAL_H
#define COMM_PAL_H

typedef struct { unsigned char idx, r, g, b; } comm_pal_t;
static const comm_pal_t comm_pal[] = {
    { 145, 17, 14, 10 },   /* desk [0] */
    { 146, 18, 15, 11 },   /* desk [1] */
    { 147, 21, 17, 13 },   /* desk [2] */
    { 148, 23, 19, 14 },   /* desk [3] */
    { 169, 0, 0, 0 },   /* torn3 [0] */
    { 177, 17, 0, 0 },   /* stopsign [0] */
    { 178, 19, 0, 0 },   /* stopsign [1] */
    { 179, 23, 21, 21 },   /* stopsign [2] */
    { 180, 24, 24, 24 },   /* stopsign [3] */
    { 181, 25, 25, 25 },   /* stopsign [4] */
    { 182, 28, 28, 28 },   /* stopsign [5] */
    { 183, 31, 31, 31 },   /* stopsign [6] */
    { 185, 2, 2, 3 },   /* pvm [0] */
    { 186, 6, 6, 7 },   /* pvm [1] */
    { 187, 15, 15, 16 },   /* pvm [2] */
    { 188, 21, 21, 22 },   /* pvm [3] */
    { 189, 25, 25, 26 },   /* pvm [4] */
    { 193, 11, 6, 5 },   /* aloha_sign [0] */
    { 194, 22, 4, 4 },   /* aloha_sign [1] */
    { 195, 17, 9, 4 },   /* aloha_sign [2] */
    { 196, 7, 14, 11 },   /* aloha_sign [3] */
    { 197, 25, 18, 6 },   /* aloha_sign [4] */
    { 198, 29, 28, 5 },   /* aloha_sign [5] */
    { 199, 31, 29, 1 },   /* aloha_sign [6] */
};
#define COMM_PAL_COUNT 24

#endif
