/* Auto-generated by tools/bake_boxes.py from desk.glb — do not edit.
 * 3 DISJOINT axis-aligned boxes covering 97.6% of the model volume.
 * Disjoint by construction (each box consumes its voxels), so the
 * renderer's centroid painter sort is exact — see chair3d.h. */
#ifndef DESK3D_H
#define DESK3D_H
#include <stdint.h>
#include "chair3d.h"        /* cbox_t, chair_face_v */

#define DESK_NBOXES 3

static const cbox_t desk_boxes[DESK_NBOXES] = {
    BOX6(-252,     0,  -112,   -98,   243,   119),
    BOX6(120,     0,  -124,   260,   243,   119),
    BOX6(-277,   243,  -124,   273,   256,   119),
};

#endif /* DESK3D_H */
