/* Auto-generated by tools/compose_desk_pvm.py — do not edit.
 * The desk bake with the PVM MONITOR (pvm3d.h box 0, no stand) seated
 * off-center on the desktop. Drawn under the PVM's world_h (0.4): desk
 * coords are scaled 0.775 to stay true-size, the monitor's scale factors
 * cancel to exactly 1. Box 0 = the monitor (carries pvm_front_tex).
 * Total model height 294 units = 0.459 cells. */
#ifndef DESK_PVM3D_H
#define DESK_PVM3D_H
#include <stdint.h>
#include "chair3d.h"

#define DESK_PVM_NBOXES 8

static const cbox_t desk_pvm_boxes[DESK_PVM_NBOXES] = {
    BOX6(  -146,   198,   -56,   -40,   294,    45),
    BOX6(  -195,     0,   -87,   -76,   188,    92),
    BOX6(    93,     0,   -96,   202,   188,    92),
    BOX6(  -215,   188,   -96,  -146,   198,    92),
    BOX6(  -146,   188,   -96,   -40,   198,    92),
    BOX6(   -40,   188,   -96,   212,   198,    92),
    WEDGE(    41,   198,   -19,   139,   207,    20,    40,   -21,   140,    21),
    WEDGE(    40,   207,   -21,   140,   217,    21,    57,     3,   123,    13),
};

#endif /* DESK_PVM3D_H */
