/* Auto-generated by tools/bake_boxes.py from pvm_stand.glb — do not edit.
 * 2 DISJOINT axis-aligned boxes covering 87.8% of the model volume.
 * Disjoint by construction (each box consumes its voxels), so the
 * renderer's centroid painter sort is exact — see chair3d.h. */
#ifndef PVM3D_H
#define PVM3D_H
#include <stdint.h>
#include "chair3d.h"        /* cbox_t, chair_face_v */

#define PVM_NBOXES 6

static const cbox_t pvm_boxes[PVM_NBOXES] = {
    BOX6(-53,   160,   -55,    53,   256,    46),
    BOX6(-53,     0,   -39,    53,     5,    41),
    BOX6(-53,     5,   -39,   -48,   160,   -34),
    BOX6(48,     5,   -39,    53,   160,   -34),
    BOX6(-53,     5,    36,   -48,   160,    41),
    BOX6(48,     5,    36,    53,   160,    41),
};

#endif /* PVM3D_H */
