/* Auto-generated by tools/bake_boxes.py from sega_master_system.glb — do not edit.
 * 2 DISJOINT axis-aligned boxes covering 96.0% of the model volume.
 * Disjoint by construction (each box consumes its voxels), so the
 * renderer's centroid painter sort is exact — see chair3d.h. */
#ifndef SMS3D_H
#define SMS3D_H
#include <stdint.h>
#include "chair3d.h"        /* cbox_t, chair_face_v */

#define SMS_NBOXES 2

static const cbox_t sms_boxes[SMS_NBOXES] = {
    {   -41,     0,   -30,    41,   210,    36 },
    {   -29,   210,     0,    31,   254,    26 },
};

#endif /* SMS3D_H */
