#!/usr/bin/env python3
"""Bake audio into headerless IMA ADPCM for the 32X hello stream.

4 bits per sample, 2:1 vs the 8-bit PCM bakes, and — the reason it
exists — the decoder is ~15 cycles/sample of table lookups that fit
entirely in the SH-2's 4 KB cache. Speex hit 8 ms/frame on this
hardware (DT:1416 measured, B00253); ADPCM is the version the 23 MHz
memory system can afford.

No block headers: the ROM stream is decoded strictly sequentially and
loops whole-file, so the decoder just resets predictor/index to 0 at
the wrap, exactly like the encoder starts. Random access is impossible
and deliberately unsupported (the death-tape effect scrubs its own PCM
excerpt instead).

Usage:
  python3 tools/adpcm_bake.py sound/song.mp3 --rate 6000 \\
      --name amb_hello_adp --out sh_src/amb_hello_adp.h \\
      [--preview /tmp/preview.raw]

--preview writes the DECODED s16le stream (what the console will play):
  ffplay -f s16le -ar 6000 -ac 1 preview.raw
"""

import argparse
import pathlib
import subprocess
import struct
import sys

STEP_TABLE = [
    7, 8, 9, 10, 11, 12, 13, 14, 16, 17, 19, 21, 23, 25, 28, 31, 34, 37,
    41, 45, 50, 55, 60, 66, 73, 80, 88, 97, 107, 118, 130, 143, 157, 173,
    190, 209, 230, 253, 279, 307, 337, 371, 408, 449, 494, 544, 598, 658,
    724, 796, 876, 963, 1060, 1166, 1282, 1411, 1552, 1707, 1878, 2066,
    2272, 2499, 2749, 3024, 3327, 3660, 4026, 4428, 4871, 5358, 5894,
    6484, 7132, 7845, 8630, 9493, 10442, 11487, 12635, 13899, 15289,
    16818, 18500, 20350, 22385, 24623, 27086, 29794, 32767,
]
INDEX_TABLE = [-1, -1, -1, -1, 2, 4, 6, 8, -1, -1, -1, -1, 2, 4, 6, 8]


def ffmpeg_pcm(path, rate, volume):
    cmd = ["ffmpeg", "-y", "-v", "error", "-i", str(path),
           "-ac", "1", "-ar", str(rate),
           "-af", f"highshelf=f=3000:g=3,volume={volume}",
           "-f", "s16le", "-acodec", "pcm_s16le", "-"]
    return subprocess.check_output(cmd)


def ima_encode(samples):
    """Encode int16 samples -> nibble list, predictor/index start at 0.
    The decode below (and the C decoder in sound.c) must mirror this
    EXACTLY — same clamps, same table walk."""
    pred, index = 0, 0
    nibbles = []
    for s in samples:
        step = STEP_TABLE[index]
        diff = s - pred
        nib = 0
        if diff < 0:
            nib = 8
            diff = -diff
        if diff >= step:
            nib |= 4
            diff -= step
        if diff >= step >> 1:
            nib |= 2
            diff -= step >> 1
        if diff >= step >> 2:
            nib |= 1
        # Reconstruct exactly as the decoder will.
        delta = step >> 3
        if nib & 4: delta += step
        if nib & 2: delta += step >> 1
        if nib & 1: delta += step >> 2
        if nib & 8: pred -= delta
        else:       pred += delta
        pred = max(-32768, min(32767, pred))
        index = max(0, min(88, index + INDEX_TABLE[nib]))
        nibbles.append(nib)
    return nibbles


def ima_decode(nibbles):
    pred, index = 0, 0
    out = []
    for nib in nibbles:
        step = STEP_TABLE[index]
        delta = step >> 3
        if nib & 4: delta += step
        if nib & 2: delta += step >> 1
        if nib & 1: delta += step >> 2
        if nib & 8: pred -= delta
        else:       pred += delta
        pred = max(-32768, min(32767, pred))
        index = max(0, min(88, index + INDEX_TABLE[nib]))
        out.append(pred)
    return out


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("audio")
    ap.add_argument("--rate", type=int, default=6000)
    ap.add_argument("--volume", type=float, default=1.0)
    ap.add_argument("--name", default="amb_hello_adp")
    ap.add_argument("--out", required=True)
    ap.add_argument("--preview")
    args = ap.parse_args()

    pcm = ffmpeg_pcm(pathlib.Path(args.audio), args.rate, args.volume)
    samples = [s for (s,) in struct.iter_unpack("<h", pcm)]
    if len(samples) & 1:
        samples.append(0)          # whole bytes: two nibbles each

    nibbles = ima_encode(samples)
    # Pack two samples per byte: EVEN sample in the LOW nibble (the C
    # decoder consumes low-then-high).
    data = bytes((nibbles[i] | (nibbles[i + 1] << 4))
                 for i in range(0, len(nibbles), 2))

    if args.preview:
        dec = ima_decode(nibbles)
        with open(args.preview, "wb") as f:
            f.write(struct.pack(f"<{len(dec)}h", *dec))

    name, upper = args.name, args.name.upper()
    out = pathlib.Path(args.out)
    with open(out, "w") as f:
        f.write("/* Auto-generated by tools/adpcm_bake.py — do not edit. */\n")
        f.write(f"/* Source: {pathlib.Path(args.audio).name} */\n")
        f.write(f"#ifndef {upper}_H\n#define {upper}_H\n#include <stdint.h>\n\n")
        f.write(f"#define {upper}_SAMPLE_COUNT {len(samples)}\n")
        f.write(f"#define {upper}_SAMPLE_RATE  {args.rate}\n")
        f.write(f"#define {upper}_DATA_BYTES   {len(data)}\n\n")
        f.write(f"extern const uint8_t {name}_data[{len(data)}];\n\n#endif\n")
    with open(out.with_suffix(".c"), "w") as f:
        f.write("/* Auto-generated by tools/adpcm_bake.py — do not edit. */\n")
        f.write(f'#include "{out.name}"\n\n')
        f.write(f"const uint8_t __attribute__((aligned(4))) {name}_data[{len(data)}] = {{\n")
        for i in range(0, len(data), 16):
            f.write("    " + ",".join(f"0x{b:02x}" for b in data[i:i+16]) + ",\n")
        f.write("};\n")

    secs = len(samples) / args.rate
    print(f"{out}: {len(samples)} samples -> {len(data)} bytes "
          f"({secs:.1f}s @ {args.rate}Hz, 4-bit IMA)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
