#!/usr/bin/env python3
"""Bake images/splash_label.png into sh_src/box_label.h — a small
paletted texture sampled onto the box's FRONT face by box3d, so the
label deforms with the live 3D box (no per-frame bitmap cost, and it
keeps the hero->box hand-off continuous).

Stored 128x128, flipped vertically so texel row 0 == box BOTTOM (matches
the face's z->v mapping), 32 colours placed at CRAM 88..119. The texel
values ARE the CRAM indices, so box3d writes them straight to the
framebuffer.

Usage: tools/bake_label.py
"""
from PIL import Image

# Bake from the LIT, flat, square ortho render of the front face
# (scripts/gen_label_tex.py) — same scene lights as the hero so the tones
# match across the swap, but undistorted and void-free (correct aspect).
SRC = "/tmp/label_tex.png"
OUT = "sh_src/box_label.h"
LW = LH = 128
N = 48           # more colours so the red "X" + blue survive quantization
BASE = 88        # CRAM indices 88..135 (clear of cardboard 64-79, tape 80-87)


def main():
    im = Image.open(SRC).convert("RGB").resize((LW, LH), Image.LANCZOS)
    im = im.transpose(Image.FLIP_TOP_BOTTOM)   # row 0 = box bottom (v=0)
    q = im.quantize(colors=N, method=Image.MEDIANCUT, dither=Image.Dither.NONE)
    pal = q.getpalette()[:N * 3]
    pal5 = [(pal[i * 3] >> 3, pal[i * 3 + 1] >> 3, pal[i * 3 + 2] >> 3)
            for i in range(N)]
    # The "32X" red is a small area, so MEDIANCUT (which minimises TOTAL error,
    # and the big blue field dominates) merges it into a dark muddy maroon.
    # Re-saturate any palette entry that is clearly red-dominant but dark — the
    # X — into a vivid 32X red so it matches the hi-res hero label. Light tans
    # (cardboard/SEGA) have r >= 16 and are left alone.
    pal5 = [(16, 6, 6) if (r > g and r >= b and r < 16 and r - g >= 2) else (r, g, b)
            for (r, g, b) in pal5]
    idx = q.tobytes()                          # LW*LH values 0..N-1

    with open(OUT, "w") as f:
        f.write("/* Auto-generated by tools/bake_label.py — do not edit. */\n")
        f.write("#ifndef BOX_LABEL_H\n#define BOX_LABEL_H\n\n#include <stdint.h>\n\n")
        f.write(f"#define LABEL_W    {LW}\n")
        f.write(f"#define LABEL_H    {LH}\n")
        f.write(f"#define LABEL_N    {N}\n")
        f.write(f"#define LABEL_BASE {BASE}\n\n")
        f.write("static const uint8_t label_palette[LABEL_N][3] = {\n")
        for r, g, b in pal5:
            f.write(f"    {{{r},{g},{b}}},\n")
        f.write("};\n\n")
        f.write("/* Texel values are CRAM indices (BASE-offset) — write direct. */\n")
        f.write("static const uint8_t label_tex[LABEL_H][LABEL_W] = {\n")
        for y in range(LH):
            row = idx[y * LW:(y + 1) * LW]
            f.write("    {" + ",".join(str(BASE + v) for v in row) + "},\n")
        f.write("};\n\n#endif\n")
    print(f"wrote {OUT}: {LW}x{LH}, {N} colours at CRAM {BASE}..{BASE+N-1}")


if __name__ == "__main__":
    main()
