#!/usr/bin/env python3
"""Bake the high-res hero splash (scripts/genhero.py render) into
sh_src/box_hero_data.h — one 320x224 paletted frame, RLE'd, with its own
256-colour palette. Displayed once and held, so it can be full-res and
photoreal; only the live 3D box pays a per-frame cost.

RLE token format (decoder in box_hero.c, same as bake_box):
  ctrl & 0x80 : run  — (ctrl & 0x7F) copies of the next byte
  else        : copy — `ctrl` literal bytes follow

Usage:  tools/bake_hero.py [--src /tmp/hero.png]
"""
import argparse
from PIL import Image

FB_W, FB_H = 320, 224
OUT = "sh_src/box_hero_data.h"


def rle_encode(buf):
    out = bytearray()
    n = len(buf)
    i = 0
    lit = bytearray()

    def flush_lit():
        nonlocal lit
        k = 0
        while k < len(lit):
            chunk = lit[k:k + 127]
            out.append(len(chunk))
            out.extend(chunk)
            k += 127
        lit = bytearray()

    while i < n:
        v = buf[i]
        run = 1
        while i + run < n and buf[i + run] == v and run < 127:
            run += 1
        if run >= 3:
            flush_lit()
            out.append(0x80 | run)
            out.append(v)
            i += run
        else:
            lit.append(v)
            i += 1
    flush_lit()
    return out


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--src", default="/tmp/hero.png")
    args = ap.parse_args()

    im = Image.open(args.src).convert("RGB").resize((FB_W, FB_H), Image.LANCZOS)
    # No dither: cleaner flat cardboard + far better RLE; gradients here
    # are gentle enough that 256 colours band imperceptibly.
    q = im.quantize(colors=256, method=Image.MEDIANCUT, dither=Image.Dither.NONE)
    pal = q.getpalette()[:768]
    pal5 = [(pal[i * 3] >> 3, pal[i * 3 + 1] >> 3, pal[i * 3 + 2] >> 3)
            for i in range(256)]
    data = q.tobytes()                     # 320*224 palette indices
    rle = rle_encode(data)

    raw = FB_W * FB_H
    print(f"hero {FB_W}x{FB_H}  raw={raw}  rle={len(rle)} bytes "
          f"({len(rle)/1024:.0f} KB, {raw/len(rle):.1f}x)")

    with open(OUT, "w") as f:
        f.write("/* Auto-generated by tools/bake_hero.py — do not edit. */\n")
        f.write("#ifndef BOX_HERO_DATA_H\n#define BOX_HERO_DATA_H\n\n")
        f.write("#include <stdint.h>\n\n")
        f.write(f"#define HERO_W        {FB_W}\n")
        f.write(f"#define HERO_H        {FB_H}\n")
        f.write(f"#define HERO_PAL_N    256\n")
        f.write(f"#define HERO_DATA_LEN {len(rle)}\n\n")
        f.write("static const uint8_t hero_palette[HERO_PAL_N][3] = {\n")
        for r, g, b in pal5:
            f.write(f"    {{{r},{g},{b}}},\n")
        f.write("};\n\n")
        f.write(f"static const uint8_t hero_data[HERO_DATA_LEN] = {{\n")
        for k in range(0, len(rle), 32):
            f.write("    " + ",".join(str(b) for b in rle[k:k + 32]) + ",\n")
        f.write("};\n\n#endif\n")
    print(f"wrote {OUT}")


if __name__ == "__main__":
    main()
