#!/usr/bin/env python3
"""Bake the Sega 32X logo PNG/JPG into a palette-indexed C header for the
boot screen. Resizes/centers the source to 320×224 with black padding,
quantizes to N colors (default 32), emits two arrays:

    logo_pixels[224][320]  = palette indices (0..N-1)
    logo_palette[N][3]     = (R, G, B) tuples in 32X 5-bit-per-channel
                              format (0..31)

Also emits LOGO_PAL_BG = 0 (black), and a range of indices flagged as
"shimmer band" (the orange/yellow panel colors) for the animation
sweep at runtime.

Usage:
    tools/bake_logo.py images/32xlogo.jpg sh_src/boot_logo_data.h
"""
import argparse
import pathlib
import sys
from PIL import Image


def is_orange_yellow(r, g, b):
    """Heuristic: bright warm color = part of the panel/border shimmer
    band. Rough range covers orange (high R, mid G, low B) and yellow
    (high R, high G, low B)."""
    if r < 120: return False
    if b > 130: return False
    if g < 60:  return False
    return True


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("src")
    ap.add_argument("out")
    ap.add_argument("--colors", type=int, default=32)
    ap.add_argument("--width",  type=int, default=320)
    ap.add_argument("--height", type=int, default=224)
    args = ap.parse_args()

    src = Image.open(args.src).convert("RGB")
    sw, sh = src.size
    tw, th = args.width, args.height

    # Fit the source inside (tw, th) preserving aspect, pad black.
    scale = min(tw / sw, th / sh)
    rw = int(sw * scale)
    rh = int(sh * scale)
    resized = src.resize((rw, rh), Image.LANCZOS)
    canvas = Image.new("RGB", (tw, th), (0, 0, 0))
    canvas.paste(resized, ((tw - rw) // 2, (th - rh) // 2))

    # Reserve index 0 for pure black so the padding is index 0 with a
    # known palette slot. We quantize the rest into args.colors - 1
    # bins, then offset all indices by 1 so 0 stays for black.
    quantized = canvas.quantize(colors=args.colors - 1, method=Image.MEDIANCUT)
    pixels = list(quantized.getdata())
    pal_raw = quantized.getpalette()[:(args.colors - 1) * 3]
    palette = []
    for i in range(args.colors - 1):
        r, g, b = pal_raw[i * 3:i * 3 + 3]
        palette.append((r, g, b))

    # Identify shimmer band — the warm orange/yellow palette indices.
    # These get the runtime brightness pulse during the hold phase.
    shimmer_indices = []
    for idx, (r, g, b) in enumerate(palette):
        if is_orange_yellow(r, g, b):
            # +1 because we'll prepend the black entry.
            shimmer_indices.append(idx + 1)
    if not shimmer_indices:
        shimmer_indices = [1]  # fall back so the array isn't empty

    # Convert 0..255 8-bit RGB to 0..31 5-bit.
    pal_5bit = [(0, 0, 0)] + [(r >> 3, g >> 3, b >> 3) for r, g, b in palette]

    # Build pixels with +1 offset (black at 0).
    out_pixels = []
    for px in pixels:
        # px is an index 0..colors-2 into the quantized palette.
        # Map to our 1..colors-1 range.
        out_pixels.append(px + 1)

    with open(args.out, "w") as f:
        f.write("/* Auto-generated by tools/bake_logo.py — do not edit. */\n")
        f.write("/* Source: " + args.src + " */\n")
        f.write("#ifndef BOOT_LOGO_DATA_H\n#define BOOT_LOGO_DATA_H\n")
        f.write("#include <stdint.h>\n\n")
        f.write(f"#define LOGO_W {tw}\n")
        f.write(f"#define LOGO_H {th}\n")
        f.write(f"#define LOGO_PAL_N {args.colors}\n")
        f.write(f"#define LOGO_PAL_BG 0\n")
        f.write(f"#define LOGO_SHIMMER_COUNT {len(shimmer_indices)}\n\n")

        f.write(f"static const uint8_t logo_palette[LOGO_PAL_N][3] = {{\n")
        for r, g, b in pal_5bit:
            f.write(f"    {{{r},{g},{b}}},\n")
        f.write("};\n\n")

        f.write(f"static const uint8_t logo_shimmer_idx[LOGO_SHIMMER_COUNT] = {{\n    ")
        f.write(", ".join(str(i) for i in shimmer_indices))
        f.write("\n};\n\n")

        f.write(f"static const uint8_t logo_pixels[LOGO_H][LOGO_W] = {{\n")
        for y in range(th):
            row = out_pixels[y * tw:(y + 1) * tw]
            f.write("    {" + ",".join(str(v) for v in row) + "},\n")
        f.write("};\n\n")
        f.write("#endif\n")

    print(f"wrote {args.out}: {tw}x{th}, {args.colors} colors, "
          f"{len(shimmer_indices)} shimmer indices")


if __name__ == "__main__":
    main()
