#!/usr/bin/env python3
"""Bake images/outlet.jpg into sh_src/outlet_tex.h — a small index array for
the wall-mounted electrical-outlet decal (see draw_decals in raycast.c).

The source is a white plate on a white background, so colour-keying the
background is hopeless. Instead we auto-crop to the plate's bounding box
(everything darker than near-white), downsample, and brightness-quantize to
OUTLET_BASE+0..L-1 (0 = slot-dark, L-1 = plate-white). The decal renders as a
filled rectangle — which is what an outlet plate is.

Usage:
    tools/bake_outlet.py <out_w> <out_h> [--src ...] [--out ...] [--levels N]
"""
import argparse
from PIL import Image


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("out_w", type=int)
    ap.add_argument("out_h", type=int)
    ap.add_argument("--src", default="images/outlet.jpg")
    ap.add_argument("--out", default="sh_src/outlet_tex.h")
    ap.add_argument("--levels", type=int, default=5)
    ap.add_argument("--crop-thresh", type=int, default=244,
                    help="pixels darker than this bound the plate (drops the "
                         "near-white background margin)")
    args = ap.parse_args()

    src = Image.open(args.src).convert("RGB")
    w, h = src.size
    g = src.convert("L").load()
    minx, miny, maxx, maxy = w, h, -1, -1
    for y in range(h):
        for x in range(w):
            if g[x, y] < args.crop_thresh:
                minx = min(minx, x); miny = min(miny, y)
                maxx = max(maxx, x); maxy = max(maxy, y)
    if maxx < minx or maxy < miny:
        minx, miny, maxx, maxy = 0, 0, w - 1, h - 1
    src = src.crop((minx, miny, maxx + 1, maxy + 1))

    out = src.resize((args.out_w, args.out_h), Image.LANCZOS).load()
    L = args.levels
    rows = []
    for oy in range(args.out_h):
        row = []
        for ox in range(args.out_w):
            r, gg, b = out[ox, oy]
            lum = 0.299 * r + 0.587 * gg + 0.114 * b
            idx = int(lum * L / 256)
            row.append(max(0, min(L - 1, idx)))
        rows.append(row)

    with open(args.out, "w") as f:
        f.write("#ifndef OUTLET_TEX_H_INCLUDED\n#define OUTLET_TEX_H_INCLUDED\n")
        f.write("#include <stdint.h>\n\n")
        f.write("/* AUTO-GENERATED by tools/bake_outlet.py. Brightness-quantized\n")
        f.write(" * plate, cropped to its bounding box. Stored value is the offset\n")
        f.write(" * into the OUTLET_BASE palette ramp (0=slot-dark .. %d=plate-white). */\n" % (L - 1))
        f.write("#define OUTLET_TEX_WIDTH  %d\n" % args.out_w)
        f.write("#define OUTLET_TEX_HEIGHT %d\n\n" % args.out_h)
        f.write("static const uint8_t outlet_tex[OUTLET_TEX_HEIGHT][OUTLET_TEX_WIDTH] = {\n")
        for row in rows:
            f.write("  {" + ",".join(str(v) for v in row) + "},\n")
        f.write("};\n\n#endif\n")
    print("wrote %s (%dx%d, cropped from %dx%d to %dx%d)" %
          (args.out, args.out_w, args.out_h, w, h, maxx - minx + 1, maxy - miny + 1))


if __name__ == "__main__":
    main()
