#!/usr/bin/env python3
"""Export the cardboard box mesh + animation to sh_src/box_model.h for
native real-time rendering on the SH-2 (NOT a prerendered flipbook).

We bake out, per frame, the fully-evaluated vertex positions (so every
shape-key morph — flaps opening, trap door dropping — is already applied;
box3d just reads them), plus the per-frame camera basis. Everything is
16.16 fixed point (matches raycast.h's fx_t); the camera basis comes
straight from cam.matrix_world, so box3d.c only does dot-products + a
perspective divide per vertex.

Run headless:
  blender --background scripts/cardboard_box_32x.blend \
      --python tools/export_box.py
"""
import bpy

OUT = "sh_src/box_model.h"
FB_W, FB_H = 320, 224
NEAR = 0.04


def fx(v):
    return int(round(v * 65536.0))


def v3(co):
    return f"{{{fx(co[0])},{fx(co[1])},{fx(co[2])}}}"


def main():
    sc = bpy.context.scene
    sc.render.resolution_x = FB_W
    sc.render.resolution_y = FB_H

    box = bpy.data.objects["CardboardBox"]
    cam = sc.camera
    mesh = box.data
    nverts = len(mesh.vertices)
    faces = [tuple(p.vertices) for p in mesh.polygons]
    assert all(len(f) == 4 for f in faces), "exporter assumes quads"

    sensor = cam.data.sensor_width
    lens = cam.data.lens
    proj_x = 2.0 * lens / sensor
    proj_y = proj_x * (FB_W / FB_H)

    f0, f1 = sc.frame_start, sc.frame_end       # full 1..120 (intro + fall)
    nframes = f1 - f0 + 1
    frame_verts, cam_right, cam_up, cam_back, cam_pos = [], [], [], [], []
    for f in range(f0, f1 + 1):
        sc.frame_set(f)
        dg = bpy.context.evaluated_depsgraph_get()
        ev = box.evaluated_get(dg).data         # morphs applied
        frame_verts.append([ev.vertices[i].co.copy() for i in range(nverts)])
        mw = cam.evaluated_get(dg).matrix_world
        cam_right.append(mw.col[0].xyz.copy())
        cam_up.append(mw.col[1].xyz.copy())
        cam_back.append(mw.col[2].xyz.copy())
        cam_pos.append(mw.translation.copy())

    with open(OUT, "w") as o:
        o.write("/* Auto-generated by tools/export_box.py — do not edit. */\n")
        o.write("#ifndef BOX_MODEL_H\n#define BOX_MODEL_H\n\n")
        o.write("#include <stdint.h>\n\n")
        o.write(f"#define BOX_NVERTS  {nverts}\n")
        o.write(f"#define BOX_NFACES  {len(faces)}\n")
        o.write(f"#define BOX_NFRAMES {nframes}\n")
        o.write(f"#define BOX_INTRO_FRAMES 90   /* frames 0..89 = intro+dive; 90..{nframes-1} = fall */\n\n")
        o.write(f"#define BOX_PROJ_X  {fx(proj_x)}  /* 16.16 */\n")
        o.write(f"#define BOX_PROJ_Y  {fx(proj_y)}\n")
        o.write(f"#define BOX_NEAR    {fx(NEAR)}\n\n")

        o.write("static const uint8_t box_faces[BOX_NFACES][4] = {\n")
        for f in faces:
            o.write(f"    {{{f[0]},{f[1]},{f[2]},{f[3]}}},\n")
        o.write("};\n\n")

        # Per-frame morphed vertex positions (world space).
        o.write("static const int32_t box_verts[BOX_NFRAMES][BOX_NVERTS][3] = {\n")
        for fv in frame_verts:
            o.write("    {" + ",".join(v3(c) for c in fv) + "},\n")
        o.write("};\n\n")

        def emit_track(name, data):
            o.write(f"static const int32_t {name}[BOX_NFRAMES][3] = {{\n")
            for c in data:
                o.write(f"    {v3(c)},\n")
            o.write("};\n\n")

        emit_track("box_cam_right", cam_right)
        emit_track("box_cam_up", cam_up)
        emit_track("box_cam_back", cam_back)
        emit_track("box_cam_pos", cam_pos)
        o.write("#endif\n")

    print(f">>> wrote {OUT}: {nverts} verts, {len(faces)} faces, "
          f"{nframes} frames, proj_x={proj_x:.3f}")


main()
