#!/usr/bin/env python3
"""Export the cardboard box mesh + animation to sh_src/box_model.h for
native real-time rendering on the SH-2 (NOT a prerendered flipbook).

We bake out:
  * the 16 vertices in TWO poses (flaps open / flaps closed) so the
    SH-2 can lerp the shape-key morph itself,
  * the 9 quad faces (vertex indices),
  * the per-frame camera basis (right/up/back/pos) and morph value,
  * the projection scale + near plane.

Everything is emitted as 16.16 fixed point (matches raycast.h's fx_t).
The camera basis comes straight from cam.matrix_world, so box3d.c only
does dot-products + a perspective divide per vertex — no runtime trig
or matrix inversion.

Run headless:
  blender --background scripts/cardboard_box_32x.blend \
      --python tools/export_box.py
"""
import bpy
import math

OUT = "sh_src/box_model.h"
FB_W, FB_H = 320, 224
NEAR = 0.04


def fx(v):
    return int(round(v * 65536.0))


def v3(co):
    return f"{{{fx(co[0])},{fx(co[1])},{fx(co[2])}}}"


def main():
    sc = bpy.context.scene
    sc.render.resolution_x = FB_W
    sc.render.resolution_y = FB_H

    box = bpy.data.objects["CardboardBox"]
    cam = sc.camera
    mesh = box.data
    kb = mesh.shape_keys.key_blocks
    open_co = kb["Basis"].data          # value 0 == flaps open
    closed_co = kb["Flaps_Closed"].data  # value 1 == flaps closed
    nverts = len(mesh.vertices)
    faces = [tuple(p.vertices) for p in mesh.polygons]
    assert all(len(f) == 4 for f in faces), "exporter assumes quads"

    # Projection: square pixels, horizontal-fit sensor (W > H).
    sensor = cam.data.sensor_width
    lens = cam.data.lens
    proj_x = 2.0 * lens / sensor
    proj_y = proj_x * (FB_W / FB_H)

    # The dive completes at frame 90; genbox leaves frame_end at 120
    # (the tail just holds the final pose), so cap there.
    f0 = sc.frame_start
    f1 = min(sc.frame_end, 90)
    nframes = f1 - f0 + 1
    cam_right, cam_up, cam_back, cam_pos, morph = [], [], [], [], []
    for f in range(f0, f1 + 1):
        sc.frame_set(f)
        # matrix_world is derived; read it off the evaluated depsgraph
        # so the animated camera transform is actually applied.
        dg = bpy.context.evaluated_depsgraph_get()
        mw = cam.evaluated_get(dg).matrix_world
        cam_right.append(mw.col[0].xyz.copy())
        cam_up.append(mw.col[1].xyz.copy())
        cam_back.append(mw.col[2].xyz.copy())
        cam_pos.append(mw.translation.copy())
        morph.append(kb["Flaps_Closed"].value)

    with open(OUT, "w") as o:
        o.write("/* Auto-generated by tools/export_box.py — do not edit. */\n")
        o.write("#ifndef BOX_MODEL_H\n#define BOX_MODEL_H\n\n")
        o.write("#include <stdint.h>\n\n")
        o.write(f"#define BOX_NVERTS  {nverts}\n")
        o.write(f"#define BOX_NFACES  {len(faces)}\n")
        o.write(f"#define BOX_NFRAMES {nframes}\n\n")
        o.write(f"#define BOX_PROJ_X  {fx(proj_x)}  /* 16.16 */\n")
        o.write(f"#define BOX_PROJ_Y  {fx(proj_y)}\n")
        o.write(f"#define BOX_NEAR    {fx(NEAR)}\n\n")

        o.write("static const uint8_t box_faces[BOX_NFACES][4] = {\n")
        for f in faces:
            o.write(f"    {{{f[0]},{f[1]},{f[2]},{f[3]}}},\n")
        o.write("};\n\n")

        o.write("static const int32_t box_pose_open[BOX_NVERTS][3] = {\n")
        for i in range(nverts):
            o.write(f"    {v3(open_co[i].co)},\n")
        o.write("};\n\n")
        o.write("static const int32_t box_pose_closed[BOX_NVERTS][3] = {\n")
        for i in range(nverts):
            o.write(f"    {v3(closed_co[i].co)},\n")
        o.write("};\n\n")

        def emit_track(name, data):
            o.write(f"static const int32_t {name}[BOX_NFRAMES][3] = {{\n")
            for c in data:
                o.write(f"    {v3(c)},\n")
            o.write("};\n\n")

        emit_track("box_cam_right", cam_right)
        emit_track("box_cam_up", cam_up)
        emit_track("box_cam_back", cam_back)
        emit_track("box_cam_pos", cam_pos)

        o.write("static const int32_t box_morph[BOX_NFRAMES] = {\n    ")
        o.write(", ".join(str(fx(m)) for m in morph))
        o.write("\n};\n\n")
        o.write("#endif\n")

    print(f">>> wrote {OUT}: {nverts} verts, {len(faces)} faces, "
          f"{nframes} frames, proj_x={proj_x:.3f}")


main()
