#!/usr/bin/env python3
"""Codegen: registry.json "assets" -> sh_src/sprite_defs.h

Emits the data-driven sprite table the raycaster indexes by decal/standup kind,
so a new asset is added with a registry entry + its _tex.h and NO renderer edits
(the same move tools/gen_maps.py made for maps). The Makefile runs this whenever
registry.json or a referenced _tex.h changes.

  python3 tools/gen_assets.py
"""
import argparse, json, os, sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)

MOUNT  = {"wall": "SPRITE_MOUNT_WALL", "billboard": "SPRITE_MOUNT_BILLBOARD"}
DECODE = {"offset": "SPRITE_DECODE_OFFSET", "door": "SPRITE_DECODE_DOOR"}
FLAG   = {"animated": "SPRITE_F_ANIMATED", "lod": "SPRITE_F_LOD",
          "standalone": "SPRITE_F_STANDALONE", "colmajor": "SPRITE_F_COLMAJOR",
          "artpal": "SPRITE_F_ARTPAL"}


def die(m):
    sys.stderr.write("gen_assets: error: %s\n" % m)
    sys.exit(1)


def fxlit(v):
    s = ("%.4f" % float(v)).rstrip("0").rstrip(".")
    return "FX(%s)" % s


def emit(sprites):
    incl, seen = [], set()
    for s in sprites:
        for t in (s.get("tex"), s.get("tex_hi")):
            if t and t not in seen:
                seen.add(t); incl.append(t)

    L = ['/* AUTO-GENERATED by tools/gen_assets.py from registry.json "assets".',
         ' * Do NOT edit by hand; re-run the build to regenerate.',
         ' *',
         ' * The data-driven sprite table the raycaster indexes by kind. Add an asset',
         ' * with a registry.json "assets" entry + its _tex.h — no renderer edits. */',
         '#ifndef SPRITE_DEFS_H',
         '#define SPRITE_DEFS_H',
         '#include <stdint.h>',
         '#include "raycast.h"   /* fx_t, FX */']
    for t in incl:
        L.append('#include "%s"' % t)
    L += ['',
          '#define SPRITE_MOUNT_WALL      0   /* painted flat into the wall column */',
          '#define SPRITE_MOUNT_BILLBOARD 1   /* camera-facing free-standing standup */',
          '#define SPRITE_DECODE_OFFSET   0   /* 0 transparent, v>0 -> base + (v-1) */',
          '#define SPRITE_DECODE_DOOR     1   /* the door multi-ramp dlut */',
          '#define SPRITE_F_ANIMATED   0x01',
          '#define SPRITE_F_LOD        0x02   /* has a hi-res variant (tex_hi) */',
          '#define SPRITE_F_STANDALONE 0x04   /* free-standing (not wall-anchored) */',
          '#define SPRITE_F_COLMAJOR   0x08   /* lo-res texture stored [W][H] (door) */',
          '/* The palette holds the ARTIST\'S COLOURS, not a fog ramp of one',
          ' * material. First-party assets bake a luminance ramp, so the renderer',
          ' * shades them by walking the index down (neanderthal, outlet). Doing',
          ' * that to real art RECOLOURS it -- a torn wallpaper decal of cream',
          ' * over grey-tan lost its cream entirely and read as a sage blob. */',
          '#define SPRITE_F_ARTPAL     0x10',
          '',
          'typedef struct {',
          '    const uint8_t *tex, *tex_hi;       /* lo-res + optional hi-res (LOD) */',
          '    uint16_t w, h, w_hi, h_hi;         /* texture dims (0 hi if none) */',
          '    fx_t     world_h, world_hw, z;     /* world height, half-width, centre z */',
          '    uint8_t  base, mount, decode, flags;',
          '} sprite_def_t;',
          '',
          '/* Indexed by decal/standup kind (registry decals.kinds). */',
          'static const sprite_def_t sprite_defs[] = {']

    next_k = 0
    for s in sorted(sprites, key=lambda s: s["kind"]):
        # sprite_defs is INDEXED BY KIND, so kinds that exist only as decal
        # kinds (e.g. exit_hole: engine feature, no texture) get a zero row —
        # without the padding every later kind reads the wrong sprite.
        while next_k < s["kind"]:
            L.append('    /* (no sprite)  k%d */ '
                     '{ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 },' % next_k)
            next_k += 1
        next_k = s["kind"] + 1
        sym, pfx = s["sym"], s["sym"].upper()
        if s.get("tex_hi"):
            symhi = s["sym_hi"]; phi = symhi.upper()
            texhi, whi, hhi = "(const uint8_t*)%s" % symhi, "%s_WIDTH" % phi, "%s_HEIGHT" % phi
        else:
            texhi, whi, hhi = "0", "0", "0"
        flags = " | ".join(FLAG[f] for f in s.get("flags", [])) or "0"
        L.append('    /* %-11s k%d */ { (const uint8_t*)%s, %s, %s_WIDTH, %s_HEIGHT, %s, %s, %s, %s, %s, %s, %s, %s, %s },' % (
            s["id"], s["kind"], sym, texhi, pfx, pfx, whi, hhi,
            fxlit(s["world_h"]), fxlit(s["world_hw"]), fxlit(s["z"]),
            s["base"], MOUNT[s["mount"]], DECODE[s["decode"]], flags))

    L += ['};', '',
          '#define SPRITE_DEF_COUNT (int)(sizeof sprite_defs / sizeof sprite_defs[0])',
          '',
          '/* Kind-indexed display names for the in-ROM ASSET VIEWER. Generated so a',
          ' * community sprite is identifiable there instead of reading "ASSET" --',
          ' * the viewer is how an author checks their upload against their art. */',
          'static const char *const sprite_names[] = {']
    next_k = 0
    for s in sorted(sprites, key=lambda s: s["kind"]):
        while next_k < s["kind"]:
            L.append('    "",')
            next_k += 1
        next_k = s["kind"] + 1
        L.append('    "%s",' % s["id"].upper()[:16])
    L += ['};', '',
          '#endif /* SPRITE_DEFS_H */', '']
    return "\n".join(L)


def validate(sprites):
    if not sprites:
        die("registry has no assets.sprites")
    kinds = {}
    for s in sprites:
        for k in ("id", "kind", "mount", "sym", "base", "decode"):
            if k not in s:
                die("%s: missing %r" % (s.get("id", "?"), k))
        if s["mount"] not in MOUNT:
            die("%s: unknown mount %r" % (s["id"], s["mount"]))
        if s["decode"] not in DECODE:
            die("%s: unknown decode %r" % (s["id"], s["decode"]))
        if isinstance(s["base"], int):
            pal = s.get("pal") or []
            if not (1 <= len(pal) <= 7):
                die("%s: numeric base needs a 'pal' of 1..7 colors" % s["id"])
            if not (144 <= s["base"] and s["base"] + 8 <= 256):
                die("%s: base %d outside the community arena" % (s["id"], s["base"]))
        for f in s.get("flags", []):
            if f not in FLAG:
                die("%s: unknown flag %r" % (s["id"], f))
        if s["kind"] in kinds:
            die("kind %d used by both %s and %s" % (s["kind"], kinds[s["kind"]], s["id"]))
        kinds[s["kind"]] = s["id"]


def emit_comm_pal(sprites):
    """Community CRAM arena: every sprite carrying its own quantized palette
    (registry "pal", darkest->brightest, numeric "base") becomes rows the
    engine's build_palette paints in one loop. Texels 1..7 -> base+1..base+7,
    matching the neanderthal layout (base+0 spare for a future back color)."""
    L = ['/* AUTO-GENERATED by tools/gen_assets.py from registry.json.',
         ' * Community sprite palettes -> CRAM arena entries. Painted by',
         ' * build_palette(); do NOT edit. */',
         '#ifndef COMM_PAL_H',
         '#define COMM_PAL_H',
         '',
         'typedef struct { unsigned char idx, r, g, b; } comm_pal_t;',
         'static const comm_pal_t comm_pal[] = {']
    n = 0
    for s in sorted(sprites, key=lambda s: s["kind"]):
        base, pal = s.get("base"), s.get("pal")
        if not (isinstance(base, int) and pal):
            continue
        for i, (r, gg, b) in enumerate(pal):
            L.append('    { %d, %d, %d, %d },   /* %s [%d] */'
                     % (base + 1 + i, r, gg, b, s["id"], i))
            n += 1
    if n == 0:
        L.append('    { 0, 0, 0, 0 },   /* placeholder: keeps the array legal */')
    L += ['};', '#define COMM_PAL_COUNT %d' % n, '', '#endif', '']
    return "\n".join(L)


def select(sprites, profile):
    """Which assets this ROM ships. Community uploads (tier "community") stay
    out of the flagship: they compile only into the community ROM and into a
    contributor's own build. Dropping them is SAFE because sprite_defs is
    indexed by kind and emit() pads the gaps — every remaining kind keeps its
    index, a dropped one reads as a zero row (and lint_maps forbids a
    core/curated map from referencing one)."""
    if profile in ("core", "flagship"):
        return [s for s in sprites if s.get("tier", "core") != "community"]
    return sprites            # community + author builds get the lot


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--registry", default=os.path.join(ROOT, "registry.json"))
    ap.add_argument("--out", default=os.path.join(ROOT, "sh_src", "sprite_defs.h"))
    ap.add_argument("--profile", default="core",
                    help="core (flagship: first-party assets only) | "
                         "community | author:<handle> (both: all assets)")
    args = ap.parse_args()
    with open(args.registry) as fh:
        sprites = json.load(fh).get("assets", {}).get("sprites", [])
    validate(sprites)
    sprites = select(sprites, args.profile)
    text = emit(sprites)
    old = open(args.out).read() if os.path.exists(args.out) else None
    if old != text:
        with open(args.out, "w") as fh:
            fh.write(text)
    pal_out = os.path.join(os.path.dirname(args.out), "comm_pal.h")
    ptext = emit_comm_pal(sprites)
    pold = open(pal_out).read() if os.path.exists(pal_out) else None
    if pold != ptext:
        with open(pal_out, "w") as fh:
            fh.write(ptext)
    print("gen_assets: %d sprite(s) -> %s%s" %
          (len(sprites), args.out, "" if old != text else " (unchanged)"))


if __name__ == "__main__":
    main()
