#!/usr/bin/env python3
"""Codegen: maps/*.map (+ registry.json) -> sh_src/custom_maps.c

Parses each .map via the shared format module (tools/mapfmt.py), resolves the
human values to engine numbers using registry.json, validates the caps, and
emits one C file of POD descriptors (custom_maps[]) that compiles into the ROM.
The C side (raycast_load_custom in raycast.c) replays each descriptor.

The Makefile runs this on any .map change. Run by hand with:
    python3 tools/gen_maps.py
    python3 tools/gen_maps.py --maps maps --registry registry.json --out sh_src/custom_maps.c
"""
import argparse, glob, json, os, sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
sys.path.insert(0, HERE)
import mapfmt   # noqa: E402  (shared .map syntax)


def die(msg):
    sys.stderr.write("gen_maps: error: %s\n" % msg)
    sys.exit(1)


def fxlit(v):
    """Readable compile-time FX() literal from a number."""
    s = ("%.4f" % float(v)).rstrip("0").rstrip(".")
    return "FX(%s)" % s


def resolve(path, reg):
    """Load a .map and resolve it to the numeric dict the emitter wants."""
    base = os.path.basename(path)
    try:
        m = mapfmt.parse(open(path).read())
    except mapfmt.MapFormatError as e:
        die("%s: %s" % (base, e))

    glyphs = reg["cells"]["glyphs"]
    facing = reg["facing"]
    pstyle, pheight, pcrawl = (reg["partition"][k] for k in ("style", "height", "crawl"))
    cdir = reg["crawl"]["dir"]
    face_axis = reg["decals"]["face_axis"]
    kinds = {k["id"]: k for k in reg["decals"]["kinds"]}
    lim = reg["limits"]
    w, h = m["w"], m["h"]

    if w > lim["max_dim"] or h > lim["max_dim"]:
        die("%s: size %dx%d exceeds max_dim %d" % (base, w, h, lim["max_dim"]))
    if len(m["grid"]) != h:
        die("%s: grid has %d rows, size says %d" % (base, len(m["grid"]), h))
    cells = []
    for ri, row in enumerate(m["grid"]):
        if len(row) != w:
            die("%s: grid row %d is %d wide, size says %d" % (base, ri, len(row), w))
        for ch in row:
            if ch not in glyphs:
                die("%s: grid row %d has unknown glyph %r" % (base, ri, ch))
            cells.append(glyphs[ch])

    sp = m["spawn"]
    if sp["facing"] not in facing:
        die("%s: unknown facing %r" % (base, sp["facing"]))
    spawn = (sp["x"], sp["y"], facing[sp["facing"]])

    parts = []
    for p in m["partitions"]:
        for enum, table, what in ((p["style"], pstyle, "style"),
                                  (p["height"], pheight, "height"),
                                  (p["crawl"], pcrawl, "crawl")):
            if enum not in table:
                die("%s: unknown partition %s %r" % (base, what, enum))
        parts.append((p["x1"], p["y1"], p["x2"], p["y2"],
                      pstyle[p["style"]], pheight[p["height"]], pcrawl[p["crawl"]]))

    decals = []
    for d in m["decals"]:
        if d["kind"] not in kinds:
            die("%s: unknown decal kind %r (add it to registry.json)" % (base, d["kind"]))
        if d["face"] not in face_axis:
            die("%s: unknown face %r" % (base, d["face"]))
        z = d.get("z", kinds[d["kind"]]["z"])
        decals.append((d["x"], d["y"], z, face_axis[d["face"]], kinds[d["kind"]]["kind"]))

    crawls = []
    for c in m["crawls"]:
        if c["dir"] not in cdir:
            die("%s: unknown dir %r" % (base, c["dir"]))
        dx, dy = cdir[c["dir"]]
        crawls.append((c["cx"], c["cy"], dx, dy, c["len"]))

    for cap, lst in (("max_partitions", parts), ("max_decals", decals),
                     ("max_crawl_runs", crawls)):
        if len(lst) > lim[cap]:
            die("%s: %d items exceed %s %d" % (base, len(lst), cap, lim[cap]))

    return {"name": m["name"], "w": w, "h": h, "cells": cells, "parts": parts,
            "decals": decals, "crawls": crawls, "spawn": spawn,
            "lobby_ceiling": m["options"]["lobby_ceiling"],
            "place_outlets": m["options"]["place_outlets"],
            "place_exit_door": m["options"]["place_exit_door"]}


def emit(maps, out_path):
    L = ['/* AUTO-GENERATED by tools/gen_maps.py from the maps directory.',
         ' * Do NOT edit by hand. Re-run the build to regenerate. */',
         '#include "custom_maps.h"', '']
    total = 0
    for i, m in enumerate(maps):
        p = "map%02d" % i
        L.append("static const uint8_t %s_grid[] = {" % p)
        for r in range(m["h"]):
            row = m["cells"][r * m["w"]:(r + 1) * m["w"]]
            L.append("    " + ",".join(str(c) for c in row) + ",")
        L.append("};")
        total += m["w"] * m["h"]
        if m["parts"]:
            L.append("static const cm_partition_t %s_parts[] = {" % p)
            for (x1, y1, x2, y2, st, ht, cr) in m["parts"]:
                L.append("    { %s,%s,%s,%s, %d,%d,%d }," %
                         (fxlit(x1), fxlit(y1), fxlit(x2), fxlit(y2), st, ht, cr))
            L.append("};")
        if m["decals"]:
            L.append("static const cm_decal_t %s_decals[] = {" % p)
            for (x, y, z, ax, kd) in m["decals"]:
                L.append("    { %s,%s,%s, %d,%d }," % (fxlit(x), fxlit(y), fxlit(z), ax, kd))
            L.append("};")
        if m["crawls"]:
            L.append("static const cm_crawl_t %s_crawls[] = {" % p)
            for (cx, cy, dx, dy, ln) in m["crawls"]:
                L.append("    { %d,%d,%d,%d,%d }," % (cx, cy, dx, dy, ln))  # dx,dy signed
            L.append("};")
        L.append("")
    if maps:
        L.append("const custom_map_t custom_maps[] = {")
        for i, m in enumerate(maps):
            p = "map%02d" % i
            sx, sy, sa = m["spawn"]
            parts = ("%s_parts,%d" % (p, len(m["parts"]))) if m["parts"] else "0,0"
            decals = ("%s_decals,%d" % (p, len(m["decals"]))) if m["decals"] else "0,0"
            crawls = ("%s_crawls,%d" % (p, len(m["crawls"]))) if m["crawls"] else "0,0"
            L.append('    { "%s", %d,%d, %s_grid, %s, %s, %s, %s,%s,%d, %d,%d,%d },' %
                     (m["name"][:16], m["w"], m["h"], p, parts, decals, crawls,
                      fxlit(sx), fxlit(sy), sa,
                      m["lobby_ceiling"], m["place_outlets"], m["place_exit_door"]))
        L.append("};")
        L.append("const int custom_map_count = (int)(sizeof custom_maps / sizeof custom_maps[0]);")
    else:
        L.append("/* no maps/*.map found */")
        L.append("const custom_map_t custom_maps[1] = {{0}};")
        L.append("const int custom_map_count = 0;")
    L.append("")
    text = "\n".join(L)

    old = None
    if os.path.exists(out_path):
        with open(out_path) as fh:
            old = fh.read()
    if old != text:
        with open(out_path, "w") as fh:
            fh.write(text)
    print("gen_maps: %d map(s), %d grid bytes -> %s%s" %
          (len(maps), total, out_path, "" if old != text else " (unchanged)"))


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--maps", default=os.path.join(ROOT, "maps"))
    ap.add_argument("--registry", default=os.path.join(ROOT, "registry.json"))
    ap.add_argument("--out", default=os.path.join(ROOT, "sh_src", "custom_maps.c"))
    args = ap.parse_args()

    with open(args.registry) as fh:
        reg = json.load(fh)
    files = sorted(glob.glob(os.path.join(args.maps, "*.map")))
    maps = [resolve(p, reg) for p in files]
    emit(maps, args.out)


if __name__ == "__main__":
    main()
