#!/usr/bin/env python3
"""Generate sh_src/sms_font.h from md_src/font.s.

The SMS mini-game's TILEBUF holds MD tile ids, and the Genesis VDP renders
them through font_data in md_src/font.s. When the SH-2 draws that same picture
into the 32X framebuffer it must use THE SAME GLYPHS, or the two renderers
disagree -- which matters because the zoom-into-the-glass transition hands off
between them at full screen, where any difference is a visible pop.

The SH-2's own font (sh_src/font.c) is a different hand-drawn 8x8 set: same
alphabet, different art (6px centred vs 5px left-aligned, 37 of 45 glyphs
differ). Matching them by eye would be a second source of truth that drifts on
the next edit to either. So this generates one from the other.

The index IS the tile id -- font_data[N] is what tile N draws, so no
reconciliation table is needed on the SH-2 side either.

Format in: 4bpp Genesis tiles, 8 longs each (one long per row, 8 nibbles,
nibble 0 leftmost). The font is strictly 2-colour (every nibble is 0 or 15),
so the 1bpp output below is lossless.
"""
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "md_src" / "font.s"
OUT = ROOT / "sh_src" / "sms_font.h"


def main() -> int:
    text = SRC.read_text()
    longs = [int(x, 16) for x in re.findall(r"\.long\s+0x([0-9A-Fa-f]{8})", text)]
    if len(longs) % 8:
        print(f"gen_sms_font: {SRC} has {len(longs)} longs, not a multiple of 8",
              file=sys.stderr)
        return 1
    tiles = len(longs) // 8

    rows = []
    for t in range(tiles):
        packed = []
        for r in range(8):
            v = longs[t * 8 + r]
            bits = 0
            for px in range(8):
                nib = (v >> (28 - 4 * px)) & 0xF
                if nib not in (0, 15):
                    print(f"gen_sms_font: tile {t} row {r} has nibble {nib}; "
                          "the font is no longer 2-colour and 1bpp would lose it",
                          file=sys.stderr)
                    return 1
                if nib:
                    bits |= 0x80 >> px
            packed.append(bits)
        rows.append(packed)

    body = [
        "/* AUTO-GENERATED by tools/gen_sms_font.py from md_src/font.s.",
        " * Do not edit; edit the MD font and rebuild.",
        " *",
        " * The Genesis VDP draws the SMS mini-game's TILEBUF through these exact",
        " * glyphs. The SH-2 renders the same picture into the 32X framebuffer, and",
        " * the zoom transition hands off between the two at full screen -- so they",
        " * share one source rather than two that agree today. Index IS the tile id.",
        " */",
        "#ifndef SMS_FONT_H",
        "#define SMS_FONT_H",
        "",
        "#include <stdint.h>",
        "",
        f"#define SMS_FONT_TILES {tiles}",
        "",
        f"static const uint8_t sms_font[SMS_FONT_TILES][8] = {{",
    ]
    for t, packed in enumerate(rows):
        vals = ",".join(f"0x{b:02X}" for b in packed)
        body.append(f"    /* {t:2d} */ {{{vals}}},")
    body += ["};", "", "#endif /* SMS_FONT_H */", ""]

    OUT.write_text("\n".join(body))
    print(f"gen_sms_font: {tiles} tiles -> {OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
