/* speex_bake — encode a mono 8 kHz s16le raw stream into raw CBR Speex
 * narrowband frames and emit them as a C array for the 32X ROM.
 *
 * Raw frames, no Ogg container: in CBR every frame encodes to the same
 * byte count, so the ROM data is just N fixed-size records and the SH-2
 * decoder can seek/loop by frame index with zero parsing.
 *
 * Build (host only, never cross-compiled):
 *   cc -O2 -I/opt/homebrew/include -L/opt/homebrew/lib -lspeex \
 *      -o tools/speex_bake tools/speex_bake.c
 *
 * Usage:
 *   ffmpeg -i song.mp3 -ac 1 -ar 8000 -f s16le -acodec pcm_s16le - | \
 *     tools/speex_bake --quality 4 --name amb_hello_spx \
 *       --out sh_src/amb_hello_spx.h [--preview preview.raw]
 *
 * --preview additionally round-trips the encoded frames through the
 * decoder and writes s16le/8kHz raw PCM — what the console will produce,
 * listenable via: ffplay -f s16le -ar 8000 -ac 1 preview.raw
 */

#include <speex/speex.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#define FRAME_SAMPLES 160   /* narrowband: 20 ms at 8 kHz */

int main(int argc, char **argv) {
    int quality = 4;
    const char *name = "amb_hello_spx";
    const char *out_path = NULL;
    const char *preview_path = NULL;

    for (int i = 1; i < argc; i++) {
        if (!strcmp(argv[i], "--quality") && i + 1 < argc) quality = atoi(argv[++i]);
        else if (!strcmp(argv[i], "--name") && i + 1 < argc) name = argv[++i];
        else if (!strcmp(argv[i], "--out") && i + 1 < argc) out_path = argv[++i];
        else if (!strcmp(argv[i], "--preview") && i + 1 < argc) preview_path = argv[++i];
        else { fprintf(stderr, "unknown arg: %s\n", argv[i]); return 1; }
    }
    if (!out_path) { fprintf(stderr, "--out required\n"); return 1; }

    void *enc = speex_encoder_init(&speex_nb_mode);
    speex_encoder_ctl(enc, SPEEX_SET_QUALITY, &quality);
    int vbr = 0, complexity = 10;
    speex_encoder_ctl(enc, SPEEX_SET_VBR, &vbr);
    speex_encoder_ctl(enc, SPEEX_SET_COMPLEXITY, &complexity);

    void *dec = NULL;
    FILE *preview = NULL;
    if (preview_path) {
        dec = speex_decoder_init(&speex_nb_mode);
        int enh = 1;
        speex_decoder_ctl(dec, SPEEX_SET_ENH, &enh);
        preview = fopen(preview_path, "wb");
        if (!preview) { perror(preview_path); return 1; }
    }

    SpeexBits bits;
    speex_bits_init(&bits);

    unsigned char *blob = NULL;
    size_t blob_len = 0, blob_cap = 0;
    int frame_bytes = -1, frames = 0;

    short pcm[FRAME_SAMPLES];
    unsigned char encoded[256];
    for (;;) {
        size_t got = fread(pcm, sizeof(short), FRAME_SAMPLES, stdin);
        if (got == 0) break;
        /* Zero-pad the tail frame to a full 20 ms. */
        for (size_t i = got; i < FRAME_SAMPLES; i++) pcm[i] = 0;

        speex_bits_reset(&bits);
        speex_encode_int(enc, pcm, &bits);
        int n = speex_bits_write(&bits, (char *)encoded, sizeof(encoded));
        if (frame_bytes < 0) frame_bytes = n;
        if (n != frame_bytes) {
            fprintf(stderr, "CBR violated: frame %d is %d bytes, expected %d\n",
                    frames, n, frame_bytes);
            return 1;
        }
        if (blob_len + n > blob_cap) {
            blob_cap = blob_cap ? blob_cap * 2 : 65536;
            blob = realloc(blob, blob_cap);
        }
        memcpy(blob + blob_len, encoded, n);
        blob_len += n;
        frames++;

        if (dec) {
            short back[FRAME_SAMPLES];
            SpeexBits dbits;
            speex_bits_init_buffer(&dbits, encoded, n);
            speex_decode_int(dec, &dbits, back);
            fwrite(back, sizeof(short), FRAME_SAMPLES, preview);
        }
        if (got < FRAME_SAMPLES) break;
    }

    /* Header (.h) + data (.c), matching wav_to_pwm.py conventions. */
    char upper[128];
    for (size_t i = 0; i <= strlen(name); i++)
        upper[i] = name[i] >= 'a' && name[i] <= 'z' ? name[i] - 32 : name[i];

    FILE *h = fopen(out_path, "w");
    if (!h) { perror(out_path); return 1; }
    fprintf(h, "/* Auto-generated by tools/speex_bake.c — do not edit. */\n");
    fprintf(h, "#ifndef %s_H\n#define %s_H\n#include <stdint.h>\n\n", upper, upper);
    fprintf(h, "#define %s_FRAME_BYTES   %d\n", upper, frame_bytes);
    fprintf(h, "#define %s_FRAME_COUNT   %d\n", upper, frames);
    fprintf(h, "#define %s_FRAME_SAMPLES %d\n", upper, FRAME_SAMPLES);
    fprintf(h, "#define %s_SAMPLE_RATE   8000\n", upper);
    fprintf(h, "#define %s_QUALITY       %d\n\n", upper, quality);
    fprintf(h, "extern const uint8_t %s_frames[%zu];\n\n#endif\n",
            name, blob_len);
    fclose(h);

    char c_path[1024];
    snprintf(c_path, sizeof(c_path), "%s", out_path);
    char *dot = strrchr(c_path, '.');
    if (dot) strcpy(dot, ".c");
    FILE *c = fopen(c_path, "w");
    if (!c) { perror(c_path); return 1; }
    fprintf(c, "/* Auto-generated by tools/speex_bake.c — do not edit. */\n");
    fprintf(c, "#include \"%s\"\n\n", strrchr(out_path, '/') ?
            strrchr(out_path, '/') + 1 : out_path);
    fprintf(c, "const uint8_t __attribute__((aligned(4))) %s_frames[%zu] = {\n",
            name, blob_len);
    for (size_t i = 0; i < blob_len; i += 16) {
        fprintf(c, "    ");
        for (size_t j = i; j < i + 16 && j < blob_len; j++)
            fprintf(c, "0x%02x,", blob[j]);
        fprintf(c, "\n");
    }
    fprintf(c, "};\n");
    fclose(c);

    fprintf(stderr, "%s: %d frames x %d bytes = %zu bytes (%.1fs @ q%d)\n",
            out_path, frames, frame_bytes, blob_len,
            frames * FRAME_SAMPLES / 8000.0, quality);
    return 0;
}
