#!/usr/bin/env python3
"""Convert a WAV to a 32X PWM sample header.

The 32X's PWM hardware takes 10-bit duty-cycle compare values packed
into 16-bit registers. d32xr's `marssound.c` uses the range
[SAMPLE_MIN=2, SAMPLE_MAX=1032] centered at 517. We pre-bake the
samples in that format so the DMA can stream them straight into
MARS_PWM_MONO (or MARS_PWM_LEFT/RIGHT) without per-sample CPU work.

Pipeline:
  1. ffmpeg decodes the WAV at the target rate as mono signed 16-bit
     little-endian PCM. Trim window controlled by --start / --length.
  2. Each int16 sample is rescaled to [SAMPLE_MIN, SAMPLE_MAX].
  3. The result is emitted as a `const uint16_t name_samples[N]`
     array in a C header, 16-byte aligned (DMA source must be aligned).

Usage:
  python3 tools/wav_to_pwm.py \\
      "sound/whatever.wav" \\
      --start 4.0 --length 1.5 --rate 11025 \\
      --name amb_buzz --out sh_src/amb_buzz.h
"""

import argparse
import pathlib
import struct
import subprocess
import sys

SAMPLE_MIN = 2
SAMPLE_MAX = 1032
SAMPLE_CENTER = (SAMPLE_MAX + SAMPLE_MIN) // 2     # 517
SAMPLE_HALFSPAN = (SAMPLE_MAX - SAMPLE_MIN) // 2   # 515


def ffmpeg_to_mono_pcm(wav_path: pathlib.Path, rate: int,
                      start: float, length: float, volume: float) -> bytes:
    """Trim, mono-mix, resample, gain-adjust; return raw s16le PCM."""
    af_chain = f"volume={volume}"
    cmd = [
        "ffmpeg", "-y", "-v", "error",
        "-i", str(wav_path),
        "-ss", f"{start}",
        "-t", f"{length}",
        "-ac", "1",                  # downmix to mono
        "-ar", str(rate),
        "-af", af_chain,
        "-f", "s16le",
        "-acodec", "pcm_s16le",
        "-",
    ]
    return subprocess.check_output(cmd)


def pcm_to_pwm_words(pcm_bytes: bytes) -> list[int]:
    """Output uint16_t in the PWM duty-cycle range [SAMPLE_MIN, SAMPLE_MAX]."""
    words = []
    for (s,) in struct.iter_unpack("<h", pcm_bytes):
        v = SAMPLE_CENTER + (s * SAMPLE_HALFSPAN) // 32768
        if v < SAMPLE_MIN: v = SAMPLE_MIN
        if v > SAMPLE_MAX: v = SAMPLE_MAX
        words.append(v)
    return words


def pcm_to_int8(pcm_bytes: bytes) -> list[int]:
    """Output int8_t (-128..127) — signed offset from PWM center, must
    be left-shifted by 2 at runtime to expand back into the ~10-bit
    PWM range. 50% storage of the uint16 path, ~6 dB more quantization
    noise (8-bit dynamic range vs 10-bit), which on speech sources
    just sounds like vintage analog grain."""
    out = []
    for (s,) in struct.iter_unpack("<h", pcm_bytes):
        v = s >> 8       # int16 → int8 (truncate)
        if v < -128: v = -128
        if v > 127:  v = 127
        out.append(v)
    return out


def emit_header(samples: list[int], name: str, rate: int, bits: int,
                source: str, out_path: pathlib.Path) -> None:
    n = len(samples)
    upper = name.upper()
    if bits == 16:
        ctype = "uint16_t"
        fmt = lambda w: f"0x{w:04x}"
    else:  # bits == 8
        ctype = "int8_t"
        # Render as decimal so signs are obvious
        fmt = lambda w: f"{w:4d}"

    with open(out_path, "w") as f:
        f.write(f"/* Auto-generated by tools/wav_to_pwm.py — do not edit. */\n")
        f.write(f"/* Source: {source} */\n")
        f.write(f"#ifndef {upper}_H\n#define {upper}_H\n#include <stdint.h>\n\n")
        f.write(f"#define {upper}_SAMPLE_COUNT {n}\n")
        f.write(f"#define {upper}_SAMPLE_RATE  {rate}\n")
        f.write(f"#define {upper}_SAMPLE_BITS  {bits}\n\n")
        f.write(f"extern const {ctype} {name}_samples[{n}];\n\n")
        f.write(f"#endif\n")

    data_path = out_path.with_suffix(".c")
    with open(data_path, "w") as f:
        f.write(f"/* Auto-generated by tools/wav_to_pwm.py — do not edit. */\n")
        f.write(f'#include "{out_path.name}"\n\n')
        f.write(f"const {ctype} __attribute__((aligned(16))) "
                f"{name}_samples[{n}] = {{\n")
        for i in range(0, n, 12):
            row = ", ".join(fmt(w) for w in samples[i:i + 12])
            f.write(f"    {row},\n")
        f.write("};\n")


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("wav")
    ap.add_argument("--rate", type=int, default=11025,
                    help="target PCM sample rate (Hz)")
    ap.add_argument("--start", type=float, default=0.0,
                    help="trim start offset (seconds)")
    ap.add_argument("--length", type=float, default=1.5,
                    help="loop length (seconds)")
    ap.add_argument("--volume", type=float, default=1.0,
                    help="pre-conversion gain (1.0 = unity, 3.0 = 3× louder)")
    ap.add_argument("--bits", type=int, default=16, choices=[8, 16],
                    help="output sample width (16 = uint16 PWM word, "
                         "8 = int8 signed offset — half ROM, slight grain)")
    ap.add_argument("--name", default="amb_buzz",
                    help="C identifier base for the generated symbol")
    ap.add_argument("--out", required=True,
                    help="output .h path (a sibling .c is also written)")
    args = ap.parse_args()

    wav_path = pathlib.Path(args.wav)
    if not wav_path.is_file():
        print(f"wav not found: {wav_path}", file=sys.stderr)
        return 1

    pcm = ffmpeg_to_mono_pcm(wav_path, args.rate, args.start, args.length,
                             args.volume)
    if args.bits == 16:
        samples = pcm_to_pwm_words(pcm)
    else:
        samples = pcm_to_int8(pcm)
    out_path = pathlib.Path(args.out)
    emit_header(samples, args.name, args.rate, args.bits,
                wav_path.name, out_path)

    bytes_ = len(samples) * (args.bits // 8)
    secs = len(samples) / args.rate
    print(f"Wrote {out_path} + {out_path.with_suffix('.c')}: "
          f"{len(samples)} samples ({bytes_} bytes, {secs:.2f}s @ "
          f"{args.rate}Hz / {args.bits}bit)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
